/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppcastDotxmlRouteImport } from './routes/appcast[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveTokenRouteImport } from './routes/live.$token'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppcastDotxmlRoute = AppcastDotxmlRouteImport.update({
  id: '/appcast.xml',
  path: '/appcast.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTokenRoute = LiveTokenRouteImport.update({
  id: '/live/$token',
  path: '/live/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appcast.xml': typeof AppcastDotxmlRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/sign-out': typeof SignOutRoute
  '/live/$token': typeof LiveTokenRoute
  '/live/': typeof LiveIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appcast.xml': typeof AppcastDotxmlRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/sign-out': typeof SignOutRoute
  '/live/$token': typeof LiveTokenRoute
  '/live': typeof LiveIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appcast.xml': typeof AppcastDotxmlRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/sign-out': typeof SignOutRoute
  '/live/$token': typeof LiveTokenRoute
  '/live/': typeof LiveIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appcast.xml'
    | '/dashboard'
    | '/docs'
    | '/download'
    | '/privacy'
    | '/sign-out'
    | '/live/$token'
    | '/live/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appcast.xml'
    | '/dashboard'
    | '/docs'
    | '/download'
    | '/privacy'
    | '/sign-out'
    | '/live/$token'
    | '/live'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  id:
    | '__root__'
    | '/'
    | '/appcast.xml'
    | '/dashboard'
    | '/docs'
    | '/download'
    | '/privacy'
    | '/sign-out'
    | '/live/$token'
    | '/live/'
    | '/api/auth/callback'
    | '/api/auth/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppcastDotxmlRoute: typeof AppcastDotxmlRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  PrivacyRoute: typeof PrivacyRoute
  SignOutRoute: typeof SignOutRoute
  LiveTokenRoute: typeof LiveTokenRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appcast.xml': {
      id: '/appcast.xml'
      path: '/appcast.xml'
      fullPath: '/appcast.xml'
      preLoaderRoute: typeof AppcastDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$token': {
      id: '/live/$token'
      path: '/live/$token'
      fullPath: '/live/$token'
      preLoaderRoute: typeof LiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppcastDotxmlRoute: AppcastDotxmlRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  PrivacyRoute: PrivacyRoute,
  SignOutRoute: SignOutRoute,
  LiveTokenRoute: LiveTokenRoute,
  LiveIndexRoute: LiveIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
